/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.table.DefaultTableModel;
import util.JDBCUtilities;

/**
 *
 * @author JULIAN CAMILO
 */
public class VistaCrud extends javax.swing.JFrame {

    /**
     * Creates new form VistaCrud
     */
    public VistaCrud() {
        initComponents();
        DefaultTableModel modelo = new DefaultTableModel();
        Productos.setModel(modelo);
        for (int i = 0; i < modelo.getRowCount(); i++)
             for(int j = 0; j < modelo.getColumnCount(); j++) {
                     modelo.setValueAt("", i, j);
      }
      setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Productos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Combo1 = new javax.swing.JComboBox<>();
        BotonAceptar = new javax.swing.JButton();
        BotonLimpiar = new javax.swing.JButton();
        BotonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 2, 36)); // NOI18N
        jLabel1.setText("Arquitectos OLB Constructores");

        Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ));
        Productos.setShowGrid(true);
        jScrollPane1.setViewportView(Productos);

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 2, 18)); // NOI18N
        jLabel2.setText("Tipo de requerimiento:");

        Combo1.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        Combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Requerimiento 1", "Requerimiento 2", "Requerimiento 3" }));
        Combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo1ActionPerformed(evt);
            }
        });

        BotonAceptar.setFont(new java.awt.Font("Kristen ITC", 2, 14)); // NOI18N
        BotonAceptar.setText("Aceptar");
        BotonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarActionPerformed(evt);
            }
        });

        BotonLimpiar.setFont(new java.awt.Font("Kristen ITC", 2, 14)); // NOI18N
        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });

        BotonCerrar.setFont(new java.awt.Font("Kristen ITC", 2, 14)); // NOI18N
        BotonCerrar.setText("Cerrar");
        BotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Combo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BotonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(BotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(BotonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 191, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarActionPerformed
      String Item = Combo1.getSelectedItem().toString();
      if ("Requerimiento 1".equals(Item)){
          try{
            DefaultTableModel modelo = new DefaultTableModel();
            Productos.setModel(modelo);
            Connection conex = JDBCUtilities.getConnection();
            String sql = "SELECT Ciudad_Residencia, AVG(Salario) as 'Promedio' from Lider group by Ciudad_Residencia HAVING AVG(Salario)<600000 ORDER BY AVG(Salario) DESC";
            PreparedStatement consulta = conex.prepareStatement(sql);
            ResultSet res = consulta.executeQuery();
            ResultSetMetaData rsMD= res.getMetaData();
            int cantidadcolumnas= rsMD.getColumnCount();
            modelo.addColumn("Ciudad Residencia");
            modelo.addColumn("Promedio");
            
            while(res.next()){
                Object[]filas= new Object[cantidadcolumnas];
                
                for( int i =0; i<cantidadcolumnas; i++){
                
                    filas[i]= res.getObject(i+1);
                }
                modelo.addRow(filas);
            }
        } catch (Exception e) {
            System.err.println("Se ha producido el siguiente error:" + e.getMessage());
            e.printStackTrace();
        }   
      }
      if ("Requerimiento 2".equals(Item)){
            try {
                 DefaultTableModel modelo = new DefaultTableModel();
                 Productos.setModel(modelo);
                 Connection conex2 = JDBCUtilities.getConnection();
                 String sql = "SELECT  p.ID_Proyecto, c.Proveedor from Compra c join Proyecto p on p.ID_Proyecto = c.ID_Proyecto WHERE p.Ciudad = 'Quibdo' ORDER BY  p.ID_Proyecto ASC";
                PreparedStatement consulta2 = conex2.prepareStatement(sql);
                ResultSet res2 = consulta2.executeQuery();
                ResultSetMetaData rsMD2= res2.getMetaData();
                int cantidadcolumnas= rsMD2.getColumnCount();
                modelo.addColumn("ID Proyecto");
                modelo.addColumn("Proveedor");
                while(res2.next()){
                    Object[]filas= new Object[cantidadcolumnas];
                
                    for( int i =0; i<cantidadcolumnas; i++){
                
                    filas[i]= res2.getObject(i+1);
                   }
                   modelo.addRow(filas);
                }
                res2.close();
                consulta2.close();
            } catch (Exception e) {
            System.err.println("Se ha producido el siguiente error:" + e.getMessage());
            e.printStackTrace();
        } }
        if ("Requerimiento 3".equals(Item)){
            try {
                DefaultTableModel modelo = new DefaultTableModel();
                Productos.setModel(modelo);
                Connection conex3 = JDBCUtilities.getConnection();
                String sql = "SELECT p.ID_Proyecto, mc.Nombre_Material from Proyecto p join Compra c on (p.ID_Proyecto = c.ID_Proyecto )join MaterialConstruccion mc on (mc.ID_MaterialConstruccion = c.ID_MaterialConstruccion) WHERE p.ID_Proyecto BETWEEN 5 and 15 ORDER BY  p.ID_Proyecto  ASC";
                PreparedStatement consulta3 = conex3.prepareStatement(sql);
                ResultSet res3 = consulta3.executeQuery();
                ResultSetMetaData rsMD3= res3.getMetaData();
                int cantidadcolumnas= rsMD3.getColumnCount();
                modelo.addColumn("ID Proyecto");
                modelo.addColumn("Nombre Material");
                while(res3.next()){
                    Object[]filas= new Object[cantidadcolumnas];
                
                    for( int i =0; i<cantidadcolumnas; i++){
                
                    filas[i]= res3.getObject(i+1);
                   }
                   modelo.addRow(filas);
                }
                res3.close();
                consulta3.close();
            } catch (Exception e) {
            System.err.println("Se ha producido el siguiente error:" + e.getMessage());
            e.printStackTrace();
            }
        } 
    }//GEN-LAST:event_BotonAceptarActionPerformed

    private void Combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo1ActionPerformed
        
    }//GEN-LAST:event_Combo1ActionPerformed

    private void BotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BotonCerrarActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = new DefaultTableModel();
        Productos.setModel(modelo);
        for (int i = 0; i < modelo.getRowCount(); i++)
             for(int j = 0; j < modelo.getColumnCount(); j++) {
                     modelo.setValueAt("", i, j);
      }
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    /**
     * @param args the command lne arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCrud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JButton BotonCerrar;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JComboBox<String> Combo1;
    private javax.swing.JTable Productos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
